export {default as Home} from "./Home"
export {default as About} from "./About"
export {default as Faqs} from "./Faqs"
export {default as Contact} from "./Contact"
export {default as Costs} from "./Costs"
export {default as Hashtags} from "./Hashtags"
export {default as Map} from "./Map"