export default ()=> `<h2><center>You can click on the hashtags below to view active listings and reviews</center></h2>
    <table style="width:100%">
        <tr>
        <th>Knives</th>
        <th>Guns</th>
        <th>Accessories</th>
        <th>Reviews</th>
        </tr>
        <tr>
        <td>#fixedblades</td>
        <td>#pistols</td>
        <td>#sheaths</td>
        <td>#CRKT</td>
        </tr>
        <tr>
        <td>#automatics</td>
        <td>#rifles</td>
        <td>#holsters</td>
        <td>#Glock</td>
        </tr>
        <tr>
        <td>#folding</td>
        <td>#shotguns</td>
        <td>#slings</td>
        <td>#sigsauerp320</td>
        </tr>
        <tr>
        <td>#tanto</td>
        <td>#wheelguns</td>
        <td>#tripod</td>
        <td>#ishapor</td>
        </tr>
        <tr>
        <td>#spear</td>
        <td>#ar</td>
        <td>#bipod</td>
        <td>#elchete</td>
        </tr>
        <tr>
        <td>#clippoint</td>
        <td>#Tokarev</td>
        <td>#optics</td>
        <td>#benchmade</td>
        </tr>
        <tr>
        <td>#straight</td>
        <td>#9mm</td>
        <td>#grips</td>
        <td>#edc</td>
        </tr>
        <tr>
        <td>#droppoint</td>
        <td>#45acp</td>
        <td>#magazines</td>
        <td>#homedefense</td>
        </tr>
        <tr>
        <td>#ColdSteel</td>
        <td>#Sig</td>
        <td>#magholders</td>
        <td>#beretta</td>
        </tr>
        <tr>
        <td>#Tops</td>
        <td>#Winchester</td>
        <td>#IWB</td>
        <td>#newrelease</td>
        </tr>
    </table>
    </div>`